import { PieceCamp } from "./type";

export const initPointList = [
  { x: 0, y: 0, camp: PieceCamp.Black },
  { x: 1, y: 0, camp: PieceCamp.Black },
  { x: 2, y: 0, camp: PieceCamp.Black },
  { x: 3, y: 0, camp: PieceCamp.Black },
  { x: 4, y: 0, camp: PieceCamp.Black },
  { x: 5, y: 0, camp: PieceCamp.Black },
  { x: 6, y: 0, camp: PieceCamp.Black },
  { x: 7, y: 0, camp: PieceCamp.Black },
  { x: 8, y: 0, camp: PieceCamp.Black },
  { x: 1, y: 2, camp: PieceCamp.Black },
  { x: 7, y: 2, camp: PieceCamp.Black },
  { x: 0, y: 3, camp: PieceCamp.Black },
  { x: 2, y: 3, camp: PieceCamp.Black },
  { x: 4, y: 3, camp: PieceCamp.Black },
  { x: 6, y: 3, camp: PieceCamp.Black },
  { x: 8, y: 3, camp: PieceCamp.Black },
  { x: 0, y: 9, camp: PieceCamp.Red },
  { x: 1, y: 9, camp: PieceCamp.Red },
  { x: 2, y: 9, camp: PieceCamp.Red },
  { x: 3, y: 9, camp: PieceCamp.Red },
  { x: 4, y: 9, camp: PieceCamp.Red },
  { x: 5, y: 9, camp: PieceCamp.Red },
  { x: 6, y: 9, camp: PieceCamp.Red },
  { x: 7, y: 9, camp: PieceCamp.Red },
  { x: 8, y: 9, camp: PieceCamp.Red },
  { x: 1, y: 7, camp: PieceCamp.Red },
  { x: 7, y: 7, camp: PieceCamp.Red },
  { x: 0, y: 6, camp: PieceCamp.Red },
  { x: 2, y: 6, camp: PieceCamp.Red },
  { x: 4, y: 6, camp: PieceCamp.Red },
  { x: 6, y: 6, camp: PieceCamp.Red },
  { x: 8, y: 6, camp: PieceCamp.Red },
]