import { PieceCamp } from "./type";

export const initPointList = [
  { x: 0, y: 0, camp: PieceCamp.Black, index: 0 },
  { x: 1, y: 0, camp: PieceCamp.Black, index: 1 },
  { x: 2, y: 0, camp: PieceCamp.Black, index: 2 },
  { x: 3, y: 0, camp: PieceCamp.Black, index: 3 },
  { x: 4, y: 0, camp: PieceCamp.Black, index: 4 },
  { x: 5, y: 0, camp: PieceCamp.Black, index: 3 },
  { x: 6, y: 0, camp: PieceCamp.Black, index: 2 },
  { x: 7, y: 0, camp: PieceCamp.Black, index: 1 },
  { x: 8, y: 0, camp: PieceCamp.Black, index: 0 },
  { x: 1, y: 2, camp: PieceCamp.Black, index: 5 },
  { x: 7, y: 2, camp: PieceCamp.Black, index: 5 },
  { x: 0, y: 3, camp: PieceCamp.Black, index: 6 },
  { x: 2, y: 3, camp: PieceCamp.Black, index: 6 },
  { x: 4, y: 3, camp: PieceCamp.Black, index: 6 },
  { x: 6, y: 3, camp: PieceCamp.Black, index: 6 },
  { x: 8, y: 3, camp: PieceCamp.Black, index: 6 },
  { x: 0, y: 9, camp: PieceCamp.Red, index: 0 },
  { x: 1, y: 9, camp: PieceCamp.Red, index: 1 },
  { x: 2, y: 9, camp: PieceCamp.Red, index: 2 },
  { x: 3, y: 9, camp: PieceCamp.Red, index: 3 },
  { x: 4, y: 9, camp: PieceCamp.Red, index: 4 },
  { x: 5, y: 9, camp: PieceCamp.Red, index: 3 },
  { x: 6, y: 9, camp: PieceCamp.Red, index: 2 },
  { x: 7, y: 9, camp: PieceCamp.Red, index: 1 },
  { x: 8, y: 9, camp: PieceCamp.Red, index: 0 },
  { x: 1, y: 7, camp: PieceCamp.Red, index: 5 },
  { x: 7, y: 7, camp: PieceCamp.Red, index: 5 },
  { x: 0, y: 6, camp: PieceCamp.Red, index: 6 },
  { x: 2, y: 6, camp: PieceCamp.Red, index: 6 },
  { x: 4, y: 6, camp: PieceCamp.Red, index: 6 },
  { x: 6, y: 6, camp: PieceCamp.Red, index: 6 },
  { x: 8, y: 6, camp: PieceCamp.Red, index: 6 },
]